layout_spectrum: 0.8880985889118165
typography_spectrum: 0.08590421499684453
color:
  brandStrength: 0.7858827461022884
  lightness: 0.3212661345023662
  saturation: 0.507772576296702
  rhythmicContrast: 0.12240778957493603
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/77c81050-cded-40b7-9b88-98f4ec06835b.jpg
  appId: '288651771490588'
analytics:
  google: UA-5050578-6
author:
  name: Claudio Raimondi
  url: 'http://www.ClaudioRaimondi.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3949ffa1-19a9-4a6d-b045-e0981c6739d8.jpg
name: home
navigation:
  - name: blog
    url: 'http://blog.claudioraimondi.com'
    type: external
  - name: press
    url: 'http://press.claudioraimondi.com'
    type: external
  - name: on Twitter
    url: 'http://www.twitter.com/ClaudioRaimondi'
    type: external
  - name: on LinkedIn
    url: 'https://www.linkedin.com/in/craimondi'
    type: external
  - name: Claudio Raimondi
    url: 'http://claudioraimondi.com/claudio-raimondi'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d957626-56a1-4835-8974-871475477c5b.jpg
title: CLAUDIO RAIMONDI
description: General Manager at eBay in Italy
